### ISSUE TITLE
Missing required module 'self_mobile_kmp' on the ios example app

### ISSUE THREAD

**Issue by longpham2310** [joinself/self-mobile-embedded-samples#3]
# Problem

@senagbe It works fine to me with my system below
```
Xcode Version 15.0.1 (15A507)

Cocoapods Version 1.14.2
```

**Comment by longpham2310** [comment]
@dohaivu Can you share me your system info here please?

**Comment by dohaivu** [comment]
I cloned ios samples in `https://github.com/joinself/self-mobile-embedded-samples`, but it compiled failed to me
my system:
```
Xcode: Version 15.0.1 (15A507)
Cocoapods: 1.14.2
```

**Comment by longpham2310** [comment]
it's fixed.
